Feature: Staples Account Creation
  Background:
    Given Staples Main Page is open
    When Create Account Button is clicked

  @NegativeTests @RegressionSuite @AccountCreation
  Scenario: Staples Website Account Creation Negative Workflows Verification
    Then Verify Staples Account Creation Negative Scenarios with the following Data
      | email                                                              | firstName                                                                                                                                               | lastName                                                                                                                                                | password                                                                                                                                                         | passwordConfirmation                                                                                                                                             | isValidEmail | isValidPassword | isAuthentication | description                                                         |
      | [blank]                                                            | [blank]                                                                                                                                                 | [blank]                                                                                                                                                 | 12345678qaQA                                                                                                                                                     | 12345678qaQA                                                                                                                                                     | false        | false           | false            | Empty Email, First Name, Last Name, Password, Password Confirmation |
      | test@gmail.com                                                     | First Name                                                                                                                                              | Last Name                                                                                                                                               | [blank]                                                                                                                                                          | [blank]                                                                                                                                                          | false        | false           | false            | Empty Password, Password Confirmation                               |
      | test@                                                              | First Name                                                                                                                                              | Last Name                                                                                                                                               | 12345678                                                                                                                                                         | 12345678                                                                                                                                                         | false        | false           | false            | Empty Password, Password Confirmation                               |
      | test@                                                              | First Name                                                                                                                                              | Last Name                                                                                                                                               | 12345678                                                                                                                                                         | 12345678                                                                                                                                                         | false        | false           | false            | Empty Password, Password Confirmation                               |
      | f0OZOYhIheq4C7uJIl99T5FGPK3LqKPpUTjEKlJtJsipF@co.uk                | FName                                                                                                                                                   | Name                                                                                                                                                    | 12345678qaQA                                                                                                                                                     | 12345678qaQA                                                                                                                                                     | false        | true            | false            | Email Length is 51 characters                                       |
      | KL3OvWJGjdbXWVifKy1ts3rCuK8uCDkyjfGGMV2IX4F6oVaIl6dK1kByoRZG@co.uk | FName                                                                                                                                                   | Name                                                                                                                                                    | 12345678qaQA                                                                                                                                                     | 12345678qaQA                                                                                                                                                     | false        | true            | false            | Email Length is 66 characters                                       |
      | f0OZOYhIheq4@co.uk                                                 | nh9ey02NlKd5MetZiQq9BOlC41LnL9JZTjwkWQWwD8pPh2JJJBXKWfbBPr03J8BmVQpopIEUl29eLXt1hkWoDQnIeZWPrFUP6sStH                                                   | Name                                                                                                                                                    | 12345678qaQA                                                                                                                                                     | 12345678qaQA                                                                                                                                                     | false        | true            | false            | First Name is 101 characters                                        |
      | 1kByoRZG@co.uk                                                     | 0VmGwQHU7XP1aJQXQ11JFU0rE38GS7ZClVPoVEtEPyPk6tNOb8vbzniC7k9pdkzauU2sqScUlU97GBz2ozp7FakFqq0Yr4gLDuJXcvis1QPIGYpXmcwUZtd7iEPcCqn0bVknOHtzpafFColVnPj0bjR | Name                                                                                                                                                    | 12345678qaQA                                                                                                                                                     | 12345678qaQA                                                                                                                                                     | false        | true            | false            | First Name is 151 characters                                        |
      | f0OZOYhIheq4@co.uk                                                 | First Name                                                                                                                                              | hYqtohqvLTPG9nEAG55msSqL2r1ePRIt6P1Lb3nrrWa47IBHd4ePgMUPnJiqTyWkIdrBD4YMqL4PJBKa5Zs2mK7RCVdt64x7jTS0P                                                   | 12345678qaQA                                                                                                                                                     | 12345678qaQA                                                                                                                                                     | false        | true            | false            | Last Name is 101 characters                                         |
      | 1kByoRZG@co.uk                                                     | First Name                                                                                                                                              | XnGGgNNXcnTCmZ3JMKLI6MMWJD8P9p3tUiDhwOy1VXSkC9ix9wkEKmd5kddsFk5hnZH4q4BppzAc5c9MYpV9TKok2nQ9oVzOVSJawM4CKE8M7oV6txx5XHh6Sa8SmloXFQZE5lWaSr4EV4ca1eBJKoc | 12345678qaQA                                                                                                                                                     | 12345678qaQA                                                                                                                                                     | false        | true            | false            | Last Name is 151 characters                                         |
      | f0OZOYhIheq4@co.uk                                                 | First Name                                                                                                                                              | Name                                                                                                                                                    | t7XnCAdO6j86HWjxmDwdpp8dstjFnmU09N4ZcLSyrcZxkgTgkwT431IUZThxJgHWimvrQdozWLc5YKiKwApv5hUB5TL30zIyIopVjsZOaKrwlSgy5PgVtSxYl48XpbkKk                                | t7XnCAdO6j86HWjxmDwdpp8dstjFnmU09N4ZcLSyrcZxkgTgkwT431IUZThxJgHWimvrQdozWLc5YKiKwApv5hUB5TL30zIyIopVjsZOaKrwlSgy5PgVtSxYl48XpbkKk                                | false        | true            | false            | Password is 129 characters                                          |
      | 1kByoRZG@co.uk                                                     | First Name                                                                                                                                              | Name                                                                                                                                                    | Q3EWJ5hq97OUJVCwrcrKHrXro3dl0SxCnrdssQURXXWSEsoaqNzFveZ0QmFUhr8c1fqkbDE1eTiT1NPPa5qvfG3OpQoy5ZPnyxJWbZlT5Wg9MD6xPM92ZRSpUt0n0MqxL3kQJyQSWMFc4X2UCnFX9LEqF8Iz7brB | Q3EWJ5hq97OUJVCwrcrKHrXro3dl0SxCnrdssQURXXWSEsoaqNzFveZ0QmFUhr8c1fqkbDE1eTiT1NPPa5qvfG3OpQoy5ZPnyxJWbZlT5Wg9MD6xPM92ZRSpUt0n0MqxL3kQJyQSWMFc4X2UCnFX9LEqF8Iz7brB | false        | true            | false            | Password is 160 characters                                          |

  @RegressionSuite @AccountCreation
  Scenario: Staples Website Account Creation Positive Workflows Verification
    And User Account with following Data is created
      |  |
      |  |
      |  |
    Given Staples Main Page is open
    Then User Account should be created successfully